export const INIT_WS = 'INIT_WS';
export const SUCCESS = '_SUCCESS';
export const ERROR = '_ERROR';
export const ON_CHANGE_MESSAGE = 'ON_CHANGE_MESSAGE';
export const MESSAGE_RECIEVE = 'MESSAGE_RECIEVE';
export const SWITCH_REGISTER_MODE = 'SWITCH_REGISTER_MODE';
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
